server:
  addr : 0.0.0.0
  port: 8080
  # debug info warn error
  loglevel: debug
  profile: test
  configPath: .\configs
  logPath: .\log
  logName:  test
swagger:
  enable: true
  ui_path: /swagger/
  json_path: /swagger/doc.json
pprof:
  enable: true
  port: 6060